imitation_learning_laikago:
  robot: "laikago"
  seed: 0
  num_robot: 2
  mode: "train"
  output_dir: "output"
  num_test_episodes: 100 # test times
  total_timesteps: 200000000 # train times
  int_save_freq: 0 # specifies the frequency for saving intermediate policies every n policy steps.

  timestep_per_actorbach: 4096
  optim_batchsize: 256
  enable_env_randomizer: True

  motion_file: "OpenRoboRL/envs/quadruped_robot/task/motions/laikago_pace.txt"
  model_file: "OpenRoboRL/envs/quadruped_robot/task/policies/laikago_pace.zip"
  # model_file: "model.zip"
  # model_file: ""

imitation_learning_minicheetah:
  robot: "mini_cheetah"
  seed: 0
  num_robot: 2
  mode: "test"
  output_dir: "output"
  num_test_episodes: 100 # test times
  total_timesteps: 200000000 # train times
  int_save_freq: 0 # specifies the frequency for saving intermediate policies every n policy steps.

  timestep_per_actorbach: 4096
  optim_batchsize: 256
  enable_env_randomizer: True

  motion_file: "OpenRoboRL/envs/quadruped_robot/task/motions/minicheetah_trot.txt"
  model_file: "OpenRoboRL/envs/quadruped_robot/task/policies/minicheetah_trot.zip"
  # model_file: "model.zip"
  # model_file: ""
